### ISSUE TITLE
cargo install error

### ISSUE THREAD

**Issue by sweetmainW** [oleiade/motus#1]
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> C:\Users\xxxxx\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\motus-0.2.0\src/lib.rs:1:12
  |
1 | #![feature(iter_intersperse)]
  |            ^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `motus` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...

cargo 1.70.0 (ec8a8a0ca 2023-04-25)
rustc 1.70.0 (90c541806 2023-05-31)

**Comment by oleiade** [comment]
Hey @sweetmainW 

Indeed, building motus requires the nightly compiler at the moment. I'm working on workarounds to support building using the stable compiler instead. I'll let you know here when that's the case 👍🏻

**Comment by oleiade** [comment]
Hey @sweetmainW 

The latest version in the main branch can now be compiled with the stable compiler 🙇🏻
